[tool.poetry]
name = "openai-proxy"
version = "0.1.0"
description = ""
authors = ["Robert Dargavel Smith <teticio@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.28.1"
boto3 = "^1.28.76"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
